# NAME: Christopher Cross
# EMAIL: cc28@alumni.princeton.edu
# ID: 105238261

CFLAGS = -g -Wall -Wextra
TARFILES = lab3b.py Makefile Makefile README
ID = 105238261

default:
	echo "Python executable present"

dist:
	tar -czf lab3b-$(ID).tar.gz $(TARFILES)

clean:
	rm -f *.o *.tar.gz

